---

- name: Update packages with apt
  apt:
    name: "*"
    state: latest
    update_cache: yes
  tags:
    - packages
  when: ansible_os_family == "Debian"

- name: Update packages with yum
  yum:
    name: "*"
    state: latest
    update_cache: yes
  tags:
    - packages
  when: ansible_os_family == "RedHat"